<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;


//php artisan make:request TenRequest
class TrongRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return TRUE;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
          'txtMonHoc' => 'required|unique:hctorm,monhocgi',
          'txtGiaTien' => 'required',
          'txtGiangVien' => 'required',
          'fImages' => 'required|image|max:150'
        ];
    }
    public function messages() {
//      return parent::messages(); // TODO: Change the autogenerated stub
      return [
        'txtMonHoc.required'=>'vui lòng nhập tên',
        'txtMonHoc.unique'=>'tên này đã tồn tại',
        'txtGiaTien.required'=>'vui lòng nhập giá',
        'txtGiangVien.required'=>'vui lòng nhập tên giảng viên',
        'fImages.required'=>'vui lòng chọn hình',
        'fImages.image'=>'nhập đúng định dạng hình ảnh'
      ];
    }
}
